export const CANAIS = {
  fichasList: "fichas:list",
  fichasGet: "fichas:get",
  fichasCreate: "fichas:create",
  fichasUpdate: "fichas:update",
  fichasDelete: "fichas:delete",

  respostasList: "respostas:list",
  respostasSave: "respostas:save",
  respostasSaveBatch: "respostas:saveBatch",

  familiaresList: "familiares:list",
  familiaresCreate: "familiares:create",
  familiaresUpdate: "familiares:update",
  familiaresDelete: "familiares:delete",

  documentosList: "documentos:list",
  documentosUpload: "documentos:upload",
  documentosRemover: "documentos:remover",
  documentosAbrir: "documentos:abrir",

  perfilGet: "perfil:get",
  perfilUpdate: "perfil:update",
  perfilUploadLogo: "perfil:uploadLogo",
  perfilRemoverLogo: "perfil:removerLogo",
  perfilUploadBorda: "perfil:uploadBorda",
  perfilRemoverBorda: "perfil:removerBorda",

  exportarDocx: "exportar:docx",
  exportarPdf: "exportar:pdf",
  exportarPlanejamentoDocx: "exportar:planejamentoDocx",
  exportarPlanejamentoPdf: "exportar:planejamentoPdf",
  exportarPlanoTerapeuticoDocx: "exportar:planoTerapeuticoDocx",
  exportarPlanoTerapeuticoPdf: "exportar:planoTerapeuticoPdf",
  exportarRelatorioAvaliativoDocx: "exportar:relatorioAvaliativoDocx",
  exportarRelatorioAvaliativoPdf: "exportar:relatorioAvaliativoPdf",

  planejamentosList: "planejamentos:list",
  planejamentosCriar: "planejamentos:criar",
  planejamentosAtualizar: "planejamentos:atualizar",
  planejamentosGerar: "planejamentos:gerar",
  planejamentosRemover: "planejamentos:remover",

  planosTerapeuticosList: "planosTerapeuticos:list",
  planosTerapeuticosCriar: "planosTerapeuticos:criar",
  planosTerapeuticosAtualizar: "planosTerapeuticos:atualizar",
  planosTerapeuticosGerar: "planosTerapeuticos:gerar",
  planosTerapeuticosRemover: "planosTerapeuticos:remover",

  relatoriosAvaliativosList: "relatoriosAvaliativos:list",
  relatoriosAvaliativosCriar: "relatoriosAvaliativos:criar",
  relatoriosAvaliativosAtualizar: "relatoriosAvaliativos:atualizar",
  relatoriosAvaliativosGerar: "relatoriosAvaliativos:gerar",
  relatoriosAvaliativosRemover: "relatoriosAvaliativos:remover",

  anexosList: "anexos:list",
  anexosUpload: "anexos:upload",
  anexosRemover: "anexos:remover",
  anexosAbrir: "anexos:abrir",

  agendamentosListarIntervalo: "agendamentos:listarIntervalo",
  agendamentosCriar: "agendamentos:criar",
  agendamentosRemover: "agendamentos:remover",

  backupDetectarNuvem: "backup:detectarNuvem",
  backupUsarPastaDetectada: "backup:usarPastaDetectada",
  backupEscolherPastaManual: "backup:escolherPastaManual",
  backupRemoverPasta: "backup:removerPasta",
  backupFazerAgora: "backup:fazerAgora",
  backupListar: "backup:listar",
  backupRestaurar: "backup:restaurar",
  backupRestaurarViaDialogo: "backup:restaurarViaDialogo",
  backupBaixarGuia: "backup:baixarGuia",
  backupReiniciarApp: "backup:reiniciarApp",
} as const;
